In [ ]:
import pandas as pd
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [ ]:
df.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [ ]:
df.drop('customerID', axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

**DataCleaning**

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [ ]:
df["TotalCharges"].isnull().sum()

np.int64(11)

In [ ]:
df['TotalCharges'].fillna(df['TotalCharges'].mean(), inplace=True)

/tmp/ipython-input-1854230864.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalCharges'].fillna(df['TotalCharges'].mean(), inplace=True)

In [ ]:
df['SeniorCitizen'] = df['SeniorCitizen'].astype('object')

In [ ]:
df.shape

(7043, 20)

In [ ]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df.describe()

            tenure  MonthlyCharges  TotalCharges
count  7043.000000     7043.000000   7043.000000
mean     32.371149       64.761692   2283.300441
std      24.559481       30.090047   2265.000258
min       0.000000       18.250000     18.800000
25%       9.000000       35.500000    402.225000
50%      29.000000       70.350000   1400.550000
75%      55.000000       89.850000   3786.600000
max      72.000000      118.750000   8684.800000

In [ ]:
df.value_counts('Churn')

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [ ]:
100*df['Churn'].value_counts()/len(df['Churn'])

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

In [ ]:
internet_cols = [
    'OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies'
]
for col in internet_cols:
    df[col] = df[col].replace('No internet service', 'No')
df['MultipleLines'] = df['MultipleLines'].replace('No phone service', 'No')

In [ ]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
# 1.LABEL ENCODING
binary_cols = ["Partner", "Dependents",
               "Churn", "PaperlessBilling","MultipleLines","OnlineSecurity","OnlineBackup",
    "DeviceProtection","TechSupport","StreamingTV","StreamingMovies","PhoneService","InternetService"]
df[binary_cols] = df[binary_cols].replace({"Yes": 1, "No": 0})
# 2.ONE-HOT ENCODING
ohe_cols = [  "Contract","PaymentMethod"]
df = pd.get_dummies(df, columns=ohe_cols, drop_first=True)

/tmp/ipython-input-4183064313.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[binary_cols] = df[binary_cols].replace({"Yes": 1, "No": 0})

In [ ]:
df.drop('gender', axis=1, inplace=True)

In [ ]:
df["SeniorCitizen"].value_counts()

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [ ]:
df.shape

(7043, 23)

In [ ]:
df['tenure_group'] = pd.cut(
    df['tenure'],
    bins=[0, 6, 12, 24, 60, 72],
    labels=['0-6m', '6-12m', '1-2y', '2-5y', '5y+'],
    right=True,
    include_lowest=True
)
print(df['tenure_group'].value_counts())

tenure_group
2-5y     2426
0-6m     1481
5y+      1407
1-2y     1024
6-12m     705
Name: count, dtype: int64

In [ ]:
tenure_dummies = pd.get_dummies(
    df['tenure_group'],
    prefix='tenure',
    drop_first=False
)

df = pd.concat([df.drop('tenure_group', axis=1), tenure_dummies], axis=1)

In [ ]:
df.shape

(7043, 28)

In [ ]:
df.columns

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService',
       'MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling',
       'MonthlyCharges', 'TotalCharges', 'Churn', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'InternetService_Fiber optic', 'InternetService_No', 'tenure_0-6m',
       'tenure_6-12m', 'tenure_1-2y', 'tenure_2-5y', 'tenure_5y+'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop('Churn', axis=1)
y = df['Churn']
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=42, stratify=y)
print("Train set:", X_train.shape)
print("Test set:", X_test.shape)

Train set: (4930, 27)
Test set: (2113, 27)

In [ ]:
from sklearn.preprocessing import StandardScaler
num_cols = ["MonthlyCharges","TotalCharges"]
scaler = StandardScaler()
scaler.fit(X_train[num_cols])
X_train[num_cols] = scaler.transform(X_train[num_cols])
X_test[num_cols]  = scaler.transform(X_test[num_cols])

**ML Models without Class Imbalance handling**

**Logistic regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, classification_report
lr = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
lr.fit(X_train, y_train)
# Predict on test set
y_test_pred = lr.predict(X_test)
print("Logistic Regression (Test Set)")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Recall:", recall_score(y_test, y_test_pred))
print("F1-score:", f1_score(y_test, y_test_pred))
print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_test_pred))

Logistic Regression (Test Set)
Accuracy: 0.7453857075248462
Recall: 0.8074866310160428
F1-score: 0.6274238227146814

Confusion Matrix (Test Set):
[[1122  430]
 [ 108  453]]

Classification Report (Test Set):
              precision    recall  f1-score   support

           0       0.91      0.72      0.81      1552
           1       0.51      0.81      0.63       561

    accuracy                           0.75      2113
   macro avg       0.71      0.77      0.72      2113
weighted avg       0.81      0.75      0.76      2113

**Random Forest:**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, classification_report
import numpy as np
rf_base = RandomForestClassifier( class_weight='balanced', random_state=42,)
param_dist = {
    'n_estimators': [200, 300, 500],
    'max_depth': [6, 7, 8, 9],
    'min_samples_split': [10, 15, 20],
    'min_samples_leaf': [6, 8, 10],
    'max_features': ['sqrt', 'log2']
}
random_search = RandomizedSearchCV(
    estimator=rf_base,
    param_distributions=param_dist,
    n_iter=50,
    scoring='recall',
    cv=3,
    random_state=42,
    verbose=1,
    n_jobs=-1
)

random_search.fit(X_train, y_train)
print("\nBest Parameters Found:")
print(random_search.best_params_)

print("\nBest CV Recall:")
print(random_search.best_score_)

best_rf = random_search.best_estimator_
y_test_pred = best_rf.predict(X_test)
print("Random Forest")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Recall:  ", recall_score(y_test, y_test_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

Fitting 3 folds for each of 50 candidates, totalling 150 fits

Best Parameters Found:
{'n_estimators': 200, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'log2', 'max_depth': 6}

Best CV Recall:
0.7790519877675841
Random Forest
Accuracy: 0.7562707051585423
Recall:   0.8146167557932263

Confusion Matrix:
[[1141  411]
 [ 104  457]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.74      0.82      1552
           1       0.53      0.81      0.64       561

    accuracy                           0.76      2113
   macro avg       0.72      0.77      0.73      2113
weighted avg       0.81      0.76      0.77      2113

## **XGBOOST**

In [ ]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, classification_report
import numpy as np
neg = np.sum(y_train == 0)
pos = np.sum(y_train == 1)
scale_pos_weight = neg / pos
print("scale_pos_weight:", scale_pos_weight)
xgb_no_smote = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.4,
    scale_pos_weight=scale_pos_weight,
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)
xgb_no_smote.fit(X_train, y_train)
y_test_proba = xgb_no_smote.predict_proba(X_test)[:, 1]
y_test_pred_thresh = (y_test_proba >= 0.5).astype(int)
print("Recall:", recall_score(y_test, y_test_pred_thresh))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_thresh))
y_test_pred = xgb_no_smote.predict(X_test)

print("\n===== XGBoost (NO SMOTE - Test Set) =====")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Recall:  ", recall_score(y_test, y_test_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

scale_pos_weight: 2.7691131498470947
Recall: 0.7361853832442068
Confusion Matrix:
[[1201  351]
 [ 148  413]]

===== XGBoost (NO SMOTE - Test Set) =====
Accuracy: 0.7638428774254614
Recall:   0.7361853832442068
Confusion Matrix:
[[1201  351]
 [ 148  413]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.77      0.83      1552
           1       0.54      0.74      0.62       561

    accuracy                           0.76      2113
   macro avg       0.72      0.76      0.73      2113
weighted avg       0.80      0.76      0.77      2113

**Handling Class imbalance**

In [ ]:
from imblearn.over_sampling import SMOTENC
import numpy as np
from collections import Counter
cat_features = [
    X_train.columns.get_loc(col)
    for col in X_train.columns
    if col not in ["tenure", "MonthlyCharges", "TotalCharges"]
]

smote_nc = SMOTENC(
    categorical_features=cat_features,
    sampling_strategy='minority',
    k_neighbors=5,
    random_state=42
)

X_train_resampled, y_train_resampled = smote_nc.fit_resample(
    X_train, y_train
)

print("After SMOTENC:", Counter(y_train_resampled))

After SMOTENC: Counter({0: 3622, 1: 3622})

**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
log_reg = LogisticRegression (max_iter=1000,C=1.0)
log_reg.fit(X_train_resampled, y_train_resampled)
#evaluate on test set
y_test_pred = log_reg.predict(X_test)
print("Logistic Regression (Test Set)")
print("Recall:   ", recall_score(y_test, y_test_pred))
print("Accuracy: ", accuracy_score(y_test, y_test_pred))


print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_test_pred))

Logistic Regression (Test Set)
Recall:    0.7736185383244206
Accuracy:  0.750591575958353

Confusion Matrix (Test Set):
[[1152  400]
 [ 127  434]]

Classification Report (Test Set):
              precision    recall  f1-score   support

           0       0.90      0.74      0.81      1552
           1       0.52      0.77      0.62       561

    accuracy                           0.75      2113
   macro avg       0.71      0.76      0.72      2113
weighted avg       0.80      0.75      0.76      2113

**Random Forest Classifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, classification_report
import numpy as np
rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)
param_dist = {
    'n_estimators': [200, 300, 500],
    'max_depth': [6, 7, 8, 9],
    'min_samples_split': [10, 15, 20],
    'min_samples_leaf': [6, 8, 10, 12],
    'max_features': ['sqrt', 'log2']
}
random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=50,
    scoring='recall',
    cv=3,
    random_state=42,
    verbose=1,
    n_jobs=-1
)
random_search.fit(X_train_resampled, y_train_resampled)
print("\nBest Parameters Found:")
print(random_search.best_params_)
print("\nBest CV Recall:")
print(random_search.best_score_)
best_rf = random_search.best_estimator_
y_test_pred = best_rf.predict(X_test)
print("Random Forest (Test Set)")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Recall:  ", recall_score(y_test, y_test_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

Fitting 3 folds for each of 50 candidates, totalling 150 fits

Best Parameters Found:
{'n_estimators': 200, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'max_depth': 9}

Best CV Recall:
0.8381943720497246
Random Forest (Test Set)
Accuracy: 0.7628963558920966
Recall:   0.7415329768270945
Confusion Matrix:
[[1196  356]
 [ 145  416]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.77      0.83      1552
           1       0.54      0.74      0.62       561

    accuracy                           0.76      2113
   macro avg       0.72      0.76      0.73      2113
weighted avg       0.80      0.76      0.77      2113

In [ ]:
import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
import numpy as np
xgb_clf = xgb.XGBClassifier(objective='binary:logistic',eval_metric='logloss',random_state=42,use_label_encoder=False)
param_dist = {
    'n_estimators': [100, 200, 300],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.05, 0.1, 0.2],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bytree': [0.4, 0.6, 0.8],
    'gamma': [0, 0.1, 0.3],
    'min_child_weight': [1, 3, 5]
}
# RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=xgb_clf,
    param_distributions=param_dist,
    n_iter=50,
    scoring='recall',
    cv=3,
    verbose=1,
    random_state=42,
    n_jobs=-1
)
random_search.fit(X_train_resampled, y_train_resampled)
print("\nBest Parameters Found:")
print(random_search.best_params_)

print("\nBest CV Recall:")
print(random_search.best_score_)

best_xgb = random_search.best_estimator_
print("Confusion Matrix:")
y_test_pred = best_xgb.predict(X_test)
print("XGBoost (Test Set)")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred))
print("Recall:   ", recall_score(y_test, y_test_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

Fitting 3 folds for each of 50 candidates, totalling 150 fits

Best Parameters Found:
{'subsample': 0.8, 'n_estimators': 100, 'min_child_weight': 1, 'max_depth': 6, 'learning_rate': 0.05, 'gamma': 0, 'colsample_bytree': 0.8}

Best CV Recall:
0.838466423786192
Confusion Matrix:
XGBoost (Test Set)
Accuracy: 0.7610033128253668
Precision: 0.5369393139841688
Recall:    0.7254901960784313
Confusion Matrix:
[[1201  351]
 [ 154  407]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.77      0.83      1552
           1       0.54      0.73      0.62       561

    accuracy                           0.76      2113
   macro avg       0.71      0.75      0.72      2113
weighted avg       0.79      0.76      0.77      2113

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [04:08:57] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)